version: "2.0"

services:

  scruid_druid:
    image: mmartina/docker-druid:latest
    container_name: scruid_druid
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8082"
      - "8084:8082"

  wait_for_druid:
    image: dadarek/wait-for-dependencies:latest
    container_name: wait_for_druid
    depends_on:
      - scruid_druid
    command: scruid_druid:8081 scruid_druid:8082

  delay_response:
    image: andymacdonald/clusterf-chaos-proxy:latest
    container_name: delay_response
    depends_on:
      - scruid_druid
    links:
      - scruid_druid
    environment:
      JAVA_OPTS: "-Dserver.port=8090 -Dchaos.strategy=DELAY_RESPONSE -Dchaos.strategy.delayResponse.fixedPeriod=false -Dchaos.strategy.delayResponse.random.maxSeconds=1 -Ddestination.hostProtocolAndPort=http://scruid_druid:8082"
    ports:
      - "8085:8090"

  always_fail_500:
    image: andymacdonald/clusterf-chaos-proxy:latest
    container_name: always_fail_500
    depends_on:
      - scruid_druid
    links:
      - scruid_druid
    environment:
      JAVA_OPTS: "-Dserver.port=8090 -Dchaos.strategy=INTERNAL_SERVER_ERROR -Ddestination.hostProtocolAndPort=http://scruid_druid:8082"
    ports:
      - "8086:8090"

  chaos_proxies:
    image: rwgrim/docker-noop
    depends_on:
      - always_fail_500
      - delay_response
